import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ChakraProvider } from "@chakra-ui/react";
import Head from "next/head"; // Importe o componente Head

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Otica criada com chakra",
  description: "Generated by create next app",
};

export default function RootLayout ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ChakraProvider>
      {/* Adicione as meta tags no componente Head */}
      <Head>
      <title>{metadata.title as React.ReactNode}</title>
        <meta name="description" content={metadata.description || ""} />
        {/* Adicione outras meta tags conforme necessário */}
      </Head>
      {children}
    </ChakraProvider>
  );
}
